version: '3.7'

services:
  pocketbase:
    build: .
    volumes:
      - ./pb/pb_data:/pb/pb_data
    networks:
      - pocketnet
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - pocketnet6
    depends_on:
      - pocketbase
  page1:
    build:
      context: .
      args:
      dockerfile: web/kastonia/Dockerfile

networks:
  pocketnet:


volumes:
  caddy_data:
  caddy_config:
